### ISSUE TITLE
RAK4631 Inference Microphone Continuous doesn’t update inference

### ISSUE THREAD

**Issue by nikolaskyr** [mcmchris/wisblock-edge-impulse-deployment#1]
Hello,

I've been trying the example for RAK4631 continuous audio inference.

After compiling, I notice the inference doesn't update when I speak into the microphone.

![image](https://github.com/user-attachments/assets/13b9b0ce-6064-460a-9587-11d17a988343)

Are there extra steps required?

**Comment by nikolaskyr** [comment]
For me, I also needed to add a part to initialize the RAK18003, afterwards it worked.

**Comment by mcmchris** [comment]
Sorry I couldn't come back to this sooner! Great to know you solved it. Anything else let me know please!
